// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_gen.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Worldgen {
  public static partial class WorldGen
  {
    static readonly string __ServiceName = "WorldGen";

    static readonly grpc::Marshaller<global::Worldgen.MapRequest> __Marshaller_MapRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Worldgen.MapRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Worldgen.MapData> __Marshaller_MapData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Worldgen.MapData.Parser.ParseFrom);

    static readonly grpc::Method<global::Worldgen.MapRequest, global::Worldgen.MapData> __Method_GetMap = new grpc::Method<global::Worldgen.MapRequest, global::Worldgen.MapData>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMap",
        __Marshaller_MapRequest,
        __Marshaller_MapData);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Worldgen.WorldGenReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of WorldGen</summary>
    public abstract partial class WorldGenBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Worldgen.MapData> GetMap(global::Worldgen.MapRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WorldGen</summary>
    public partial class WorldGenClient : grpc::ClientBase<WorldGenClient>
    {
      /// <summary>Creates a new client for WorldGen</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public WorldGenClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WorldGen that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public WorldGenClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected WorldGenClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected WorldGenClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Worldgen.MapData GetMap(global::Worldgen.MapRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetMap(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Worldgen.MapData GetMap(global::Worldgen.MapRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMap, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Worldgen.MapData> GetMapAsync(global::Worldgen.MapRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetMapAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Worldgen.MapData> GetMapAsync(global::Worldgen.MapRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMap, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override WorldGenClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WorldGenClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(WorldGenBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetMap, serviceImpl.GetMap).Build();
    }

  }
}
#endregion
