# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import world_gen_pb2 as world__gen__pb2


class WorldGenStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMap = channel.unary_unary(
        '/worldgen.WorldGen/GetMap',
        request_serializer=world__gen__pb2.MapRequest.SerializeToString,
        response_deserializer=world__gen__pb2.MapData.FromString,
        )


class WorldGenServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetMap(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WorldGenServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMap': grpc.unary_unary_rpc_method_handler(
          servicer.GetMap,
          request_deserializer=world__gen__pb2.MapRequest.FromString,
          response_serializer=world__gen__pb2.MapData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'worldgen.WorldGen', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
